name: vae
channels:
  - defaults
dependencies:
  - _tflow_select=2.1.0
  - absl-py=0.9.0
  - blas=1.0
  - blinker=1.4
  - ca-certificates=2020.1.1
  - certifi=2020.4.5.1
  - cffi=1.14.0
  - chardet=3.0.4
  - click=7.1.2
  - cryptography=2.9.2
  - cudatoolkit=10.1.243
  - cudnn=7.6.5
  - google-auth-oauthlib=0.4.1
  - h5py=2.10.0
  - hdf5=1.10.4
  - icc_rt=2019.0.0
  - intel-openmp=2020.1
  - keras-applications=1.0.8
  - keras-preprocessing=1.1.0
  - libprotobuf=3.11.4
  - markdown=3.1.1
  - mkl=2020.1
  - mkl-service=2.3.0
  - mkl_fft=1.0.15
  - mkl_random=1.1.1
  - numpy-base=1.18.1
  - oauthlib=3.1.0
  - openssl=1.1.1g
  - opt_einsum=3.1.0
  - pyasn1=0.4.8
  - pycparser=2.20
  - pyjwt=1.7.1
  - pyopenssl=19.1.0
  - pyreadline=2.1
  - pysocks=1.7.1
  - python=3.7.7
  - requests-oauthlib=1.3.0
  - rsa=4.0
  - scipy=1.4.1
  - setuptools=47.1.1
  - sqlite=3.31.1
  - tensorboard=2.2.1
  - tensorflow=2.1.0
  - tensorflow-base=2.1.0
  - tensorflow-gpu=2.1.0
  - vc=14.1
  - vs2015_runtime=14.16.27012
  - wheel=0.34.2
  - win_inet_pton=1.1.0
  - wincertstore=0.2
  - zlib=1.2.11
  - pip:
    - astor==0.8.1
    - astunparse==1.6.3
    - attrs==19.3.0
    - backcall==0.1.0
    - bleach==3.1.0
    - cachetools==4.0.0
    - cloudpickle==1.3.0
    - colorama==0.4.3
    - cycler==0.10.0
    - decorator==4.4.1
    - defusedxml==0.6.0
    - entrypoints==0.3
    - future==0.18.2
    - gast==0.3.3
    - google-auth==1.10.0
    - google-pasta==0.1.8
    - grpcio==1.26.0
    - hyperopt==0.2.3
    - idna==2.8
    - imageio==2.6.1
    - importlib-metadata==1.3.0
    - ipykernel==5.1.3
    - ipython==7.11.1
    - ipython-genutils==0.2.0
    - ipywidgets==7.5.1
    - jedi==0.15.2
    - jinja2==2.10.3
    - joblib==0.14.1
    - jsonschema==3.2.0
    - jupyter==1.0.0
    - jupyter-client==5.3.4
    - jupyter-console==6.0.0
    - jupyter-core==4.6.1
    - kachery==0.4.10
    - keras==2.3.1
    - kiwisolver==1.1.0
    - markupsafe==1.1.1
    - matplotlib==3.1.2
    - mistune==0.8.4
    - more-itertools==8.0.2
    - nbconvert==5.6.1
    - nbformat==5.0.3
    - networkx==2.2
    - notebook==6.0.2
    - numpy==1.18.1
    - opencv-contrib-python==4.3.0.36
    - opencv-python==4.1.2.30
    - pandas==0.25.3
    - pandocfilters==1.4.2
    - parso==0.5.2
    - pickleshare==0.7.5
    - pillow==7.0.0
    - pip==20.1.1
    - portalocker==1.5.2
    - prometheus-client==0.7.1
    - prompt-toolkit==2.0.10
    - protobuf==3.11.2
    - pyasn1-modules==0.2.8
    - pydot==1.2.3
    - pygments==2.5.2
    - pymongo==3.10.1
    - pyparsing==2.4.6
    - pyqt5==5.14.1
    - pyqt5-sip==12.7.0
    - pyrsistent==0.15.7
    - python-dateutil==2.8.1
    - python-frontmatter==0.5.0
    - python-graphviz==0.13.2
    - pytz==2019.3
    - pywavelets==1.1.1
    - pywin32==227
    - pywinpty==0.5.7
    - pyyaml==5.3
    - pyzmq==18.1.1
    - qtconsole==4.6.0
    - requests==2.22.0
    - scikit-image==0.16.2
    - scikit-learn==0.22.1
    - send2trash==1.5.0
    - setuptools-git==1.2
    - simplejson==3.17.0
    - six==1.13.0
    - spikeextractors==0.5.4
    - spikeforest==0.11.0
    - spikesorters==0.1.3
    - spiketoolkit==0.3.6
    - tensorboard-plugin-wit==1.6.0.post3
    - tensorflow-estimator==2.2.0
    - tensorflow-gpu-estimator==2.1.0
    - termcolor==1.1.0
    - terminado==0.8.3
    - testpath==0.4.4
    - tornado==6.0.3
    - tqdm==4.44.1
    - traitlets==4.3.3
    - urllib3==1.25.7
    - wcwidth==0.1.8
    - webencodings==0.5.1
    - werkzeug==0.16.0
    - widgetsnbextension==3.5.1
    - wrapt==1.11.2
    - xmltodict==0.12.0
    - zipp==0.6.0

